### PR TITLE
Log failure msg in console.log

### PR DESCRIPTION
**Pull request by tianfeng92**
example: https://app.saucelabs.com/tests/53ad5943c45742a3bab8b340f034c36f

### CODE REVIEW

**Comment by alexplischke** [comment]
Not bad! :D

Is there any more info we can print around what step failed? Because if the spec has multiple tests, I wonder if the info we have right now is enough.

Here's what cypress natively shows:
```
 Actions
    1) .type() - type into a DOM element


  0 passing (6s)
  1 failing

  1) Actions
       .type() - type into a DOM element:

      Timed out retrying
      + expected - actual

      -'fake@email.com'
      +'fake@gemail.com'
```
Based on this info, I know that my failing step inside my spec is:
```
it('.type() - type into a DOM element', () => {...}
```

**Comment by tianfeng92** [comment]
Update to
```
- expected:  '@email.com'
+ actual:  'fake@email.com'
frame:    11 |     // https://on.cypress.io/type
  12 |     cy.get('.action-email')
> 13 |       .type('fake@email.com').should('have.value', '@email.com')
     |                               ^
  14 |
  15 |       // .type() with special character sequences
  16 |       .type('{leftarrow}{rightarrow}{uparrow}{downarrow}')
```

**Comment by tianfeng92** [comment]
See latest example: https://app.saucelabs.com/tests/d3d538c3dbc54c15a094b43be0ab3119

**Comment by alexplischke** [comment]
Perfect!

**Review by alexplischke — APPROVED** [review]

**Pull request merged**
